export const MMD_SELECTORS = {
  messageList: '#msglistview',
  messageItems: '#msglistview .item.Ai, #msglistview .item.self',
  aiItem: '.item.Ai',
  userItem: '.item.self',
  aiContent: '.content.left',
  userContent: '.content.right',
  input: '#chat-input-scope .chatMsgTextarea:not(.chat-input-collapsed-preview) textarea.uni-textarea-textarea',
  inputFallback: '#chat-input-scope textarea.uni-textarea-textarea:not([readonly])',
  inputState: '#chat-input-scope textarea.uni-textarea-textarea',
  sendProxy: '#chat-input-scope .chat-send-proxy',
  shortcutBar: '.shortcut-bar-wrapper > .shortcut-bar',
  shortcutButtons: ':scope > .shortcut-btn',
  shortcutButtonLabel: '.sb-text',
  shortcutButtonIcon: '.sb-icon img',
  instructionEntryIcon: 'ico_instruction_',
  chatSettingsEntryIcon: 'ico_chat_set_',
  instructionBar: '.shortcut-bar-wrapper > .instruction-bar',
  instructionBack: ':scope > .back-btn',
  instructionScroll: ':scope > .instruction-scroll',
  instructionChips: '.instruction-scroll .instruction-chip',
  instructionEmpty: '.instruction-scroll .instruction-empty',
  chatSettingsPanel: '.conv-style-modal',
  chatSettingsHeader: ':scope > .cs-modal-header',
  chatSettingsTitle: '.cs-header-title',
  chatSettingsClose: '.cs-header-left',
  chatSettingsSubmit: '.cs-header-right > .confirm-btn',
  chatSettingsContent: ':scope > .cs-modal-content',
  chatSettingsEmpty: '.empty-container .empty-text',
  chatSettingsGroups: '.outer-scroll-view .cs-group-card',
  chatSettingsGroupTitle: '.cs-section-title',
  chatSettingsGroupDescription: '.cs-section-subtitle',
  chatSettingsGroupCollapsedClass: 'collapsed',
  chatSettingsOptions: '.cs-style-grid > .cs-style-item:not(.fixed-item)',
  chatSettingsOptionLabel: '.style-label',
  chatSettingsOptionActiveClass: 'active',
  exitButton: '.header-box .icon-back',
  characterName: '.header-roleName',
  characterAvatar: '.header-role-img',
  characterProfile: '.header-card',
  headerActionScope: '.topTabbar > .header-icon-meun',
  headerActionButtons: ':scope > .header-meun',
  sharePopup: '.u-popup .share-popup',
  shareTitle: '.share-title',
  shareLink: '.share-sub-title',
  shareCopyButton: '.gen-link-btn',
  shareCloseButton: '.u-popup__content__close',
  modelEntry: '.mind-type',
  modelEntryIcon: '.icon-change',
  modelPanel: '.model-switch-scope',
  modelPanelTitle: '.title',
  modelFilters: '.model-filter-tab',
  modelList: '.model-list',
  modelItems: '.model-list .model-item',
  modelTitle: '.model-title',
  modelDescription: '.model-intro',
  modelBattery: '.model-battery',
  modelPermission: '.model-perm',
  modelSuccessRate: '.model-success-rate .success-badge',
  modelOptions: '.model-opt-btn',
  modelSettingIcon: 'img[src*="ico_setting2_dark.png"]',
  modelConfiguration: '.model-setting-scope',
  modelConfigurationTitle: '.mp-title',
  modelConfigurationClose: '.mp-close',
  modelConfigurationName: '.mp-model-name',
  modelConfigurationEnergy: '.mp-energy-pill',
  modelConfigurationTokenCard: '.mp-card',
  modelConfigurationTokenOptions: '.mp-token-btn',
  modelConfigurationSwitchRows: '.mp-switch-row',
  modelConfigurationSwitch: '.u-switch',
  modelConfigurationSwitchOn: '.u-switch__node--on',
  modelConfigurationPresetCards: '.mp-preset-card',
  modelConfigurationPresetOptions: '.mp-preset-item',
  modelConfigurationSubmit: '.bottom > .btn',
  moreEntry: '.more-options-scope',
  moreEntryTarget: '.btn-icon',
  morePanel: '.more-scope',
  moreItems: ':scope > .item',
  moreItemTitle: '.item-title',
  moreItemIcon: '.item-icon img',
  backgroundPanel: '.modify-scope',
  backgroundPanelTitle: '.modify-title',
  backgroundPanelItems: ':scope > .modify-item',
  customInstructionsPanel: '.custom-instruction-scope',
  customInstructionsTitle: '.header-scope .title',
  conversationPanel: '.conversation-list-scope',
  conversationTitles: ':scope > .title',
  conversationItems: '.conversation-list .conversation-item',
  conversationItemTitle: '.center-scope .title-scope > uni-view:first-child',
  conversationItemPreview: '.center-scope .content-scope',
  conversationItemAvatar: '.left-scope .avatar img',
  conversationCurrent: '.cur-conversation',
  conversationEdit: '.edit-icon',
  conversationDelete: '.delete-icon',
  conversationCreate: ':scope > .bottom > .btn',
  conversationRenameDialog: '.confirm-edit-scope',
  conversationRenameTitle: '.confirm-title',
  conversationRenameInput: 'input.uni-input-input',
  conversationRenameCancel: '.cancel-btn',
  conversationRenameOk: '.ok-btn',
  personaPanel: '.role-profile-modal',
  personaTitle: '.header-box .page-title',
  personaCancel: '.header-box .icon-back',
  personaSubmit: '.header-box .complete-btn',
  personaModes: '.radio-group > .radio-item',
  personaModeRadio: 'uni-radio',
  personaNameInput: '.card input[type="text"]',
  personaGenderItems: '.gender-box > .gender-item',
  personaGenderSelectedClass: 'active',
  personaGenderDisabledClass: 'disabled',
  personaIdentityInput: '.card.textarea-wrapper textarea',
  personaRestriction: '.forbidden-tag .tag-text',
  supplementPanel: '.role-extra-setting',
  supplementTitle: '.header-scope .page-title',
  supplementCancel: '.header-scope .icon-back',
  supplementSubmit: '.header-scope .complete-btn',
  supplementTextarea: '.textarea-wrapper textarea.uni-textarea-textarea',
  supplementPositionField: '.setting-item .picker-field',
  supplementPositionValue: '.setting-item .picker-value',
  supplementPickerContent: '.uni-picker-view-content',
  supplementPickerOptions: '.u-picker__view__column__item',
  supplementPickerSelectedClass: 'u-picker__view__column__item--selected',
  messageActionScope: '.modify-btn-scope',
  messageActionButton: ':scope > .modify-btn',
  editPanel: '.msg-modify-scope',
  editInputBox: '.modify-input-box',
  editContent: '#vditor .vditor-ir[style*="display: block"] > pre.vditor-reset[contenteditable="true"]',
  editContentFallback: '#vditor .vditor-ir > pre.vditor-reset[contenteditable="true"]',
  editOptions: '.option-box > .option-item',
  editSaveButton: '.modify-btn-box > .modify-btn',
  messageOptionPanel: '.msg-option-scope',
  messageOptionBox: '.msg-options-box',
  messageOptionItems: '.msg-options-box > .option-item',
  confirmPopup: '.u-popup__content .confirm-scope',
  confirmTitle: '.confirm-title',
  confirmContent: '.confirm-content',
  confirmCancelButton: '.confirm-bottom > .cancel-btn',
  confirmOkButton: '.confirm-bottom > .ok-btn',
} as const

export const MMD_DELETE_CONFIRM_TEXT = '删除后将无法恢复'

export const MMD_ROLLBACK_CONFIRM_TEXT = '回溯将会删除此消息下方的所有消息'
export const MMD_CONVERSATION_RENAME_TITLE = '聊天记录备注'

export const MMD_MESSAGE_OPTION_LABELS = {
  copy: '复制',
  delete: '删除',
  rollback: '回溯',
  startNewStory: '开启新的故事',
} as const

export const MMD_MESSAGE_OPTION_STRUCTURES = {
  user: [
    MMD_MESSAGE_OPTION_LABELS.copy,
    MMD_MESSAGE_OPTION_LABELS.delete,
    MMD_MESSAGE_OPTION_LABELS.rollback,
  ],
  assistant: [
    MMD_MESSAGE_OPTION_LABELS.copy,
    MMD_MESSAGE_OPTION_LABELS.delete,
    MMD_MESSAGE_OPTION_LABELS.rollback,
    MMD_MESSAGE_OPTION_LABELS.startNewStory,
  ],
} as const

export const MMD_MORE_ITEM_LABELS = {
  resetChat: '重置聊天',
  exportChat: '导出聊天',
  conversations: '新的聊天',
  editRole: '编辑角色',
  background: '更换背景',
  customInstructions: '自定义指令',
  persona: '用户人设',
  supplement: '设定补充',
  chatSettings: '对话设置',
  tutorial: '游玩教程',
} as const

export const MMD_MORE_ITEM_ICONS = {
  resetChat: 'ico_reset2_dark.png',
  exportChat: 'ico_export_dark.png',
  conversations: 'ico_rechat2_dark.png',
  editRole: 'ico_edit5_dark.png',
  background: 'ico_edit_background_dark.png',
  customInstructions: 'ico_instruction_dark.png',
  persona: 'ico_user_setting_dark.svg',
  supplement: 'ico_extra_profile_dark.svg',
  chatSettings: 'ico_chat_set_dark.svg',
  tutorial: 'ico_chat_help_dark.png',
} as const

export const MMD_TUTORIAL_ROUTE = '/pages/help/help'

export const MMD_AI_HISTORY_ACTION_COUNT = 2
export const MMD_AI_LATEST_ACTION_COUNT = 3

export const MMD_HEADER_ACTION_ICONS = {
  comments: ['ico_comment_dark.png'],
  share: ['ico_share2_dark.png'],
  favorite: ['ico_collect_dark.png'],
  refresh: ['ico_refresh2_dark.png'],
} as const

export const MMD_HEADER_ACTION_LABELS = {
  comments: ['评论', '评论区', 'comments', 'comment'],
  share: ['分享', 'share'],
  favorite: ['收藏', '已收藏', 'favorite', 'favourite', 'collect'],
  refresh: ['刷新', '刷新对话', '同步', 'refresh', 'reload', 'sync'],
} as const

export const MMD_AI_MESSAGE_ACTION_LABELS = {
  regenerate: ['重新生成', '重新回复', '重生成', 'regenerate', 'retry'],
  edit: ['编辑', '修改', 'edit', 'modify'],
  copy: ['复制', '拷贝', '分享', 'copy', 'share'],
} as const

export const MMD_AI_MESSAGE_ACTION_ICON_HINTS = {
  regenerate: ['regenerate', 'retry', 'refresh', 'reload'],
  edit: ['edit', 'modify', 'pencil'],
  copy: ['copy', 'clipboard'],
} as const

// Current MMD renders these three actions as unlabeled inline PNG data URLs.
// Their decoded dimensions provide a combined structural signature; no single
// dimension is trusted outside a complete, unique 2/3-button action group.
export const MMD_AI_MESSAGE_ACTION_ICON_SIZES = {
  regenerate: ['80x81'],
  edit: ['56x57'],
  copy: ['200x200'],
} as const
